version: "3.8"

services:
  backend:
    build: ./back-end
    ports:
      - "5001:5000"
    volumes:
      - ./back-end:/app
      - sqlite_data:/app/instance
    environment:
      FLASK_ENV: development
    # depends_on:
    #   - db

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
    depends_on:
      - backend

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: your_db_user
  #     POSTGRES_PASSWORD: your_db_password
  #     POSTGRES_DB: your_db_name
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #
volumes:
  sqlite_data:
